### ISSUE TITLE
Role Command Broke

### ISSUE THREAD

**Issue by Kitty-Therapist** [sfirfi/Bug-Bomber-600#10]
Attempted to use the role command, but the bot spat out the errors and is being SO hateful to me. :(

See #bot-logs. 

Thx.

**Comment by sfirfi** [comment]
This problem is already known since we first implemented the command, it happens if there are too many roles than what we can pump into the embed.
We will fix that when we find the time.

**Comment by sfirfi** [comment]
The bug successfully was fixed in 546b651d3a85a4ef441763c9e97a9fc6948e43ee
