### ISSUE TITLE
Rebuild config for Multiservers

### ISSUE THREAD

**Issue by sfirfi** [sfirfi/Bug-Bomber-600#14]
We're currently running a messy mix of partly Multi server content and partly single Server content. We should rebuild the Config to be completely multiserver able.
The current plan is based on [a Multiserver setup by AEnterprise](https://github.com/AEnterprise/Gearbot/blob/master/GearBot/Util/Configuration.py)

Setup summary for multiserver confs:

**Master config file**

- Bot Token
- Database Login Data
- Imgur token 
- The cat API token
- Global Admins (For maintenance commands)

**Serverwise configs**

- Prefix
- Cooldowns
- muted role
- announce channel

**Comment by AEnterprise** [comment]
might be worth to then also turn the master config into a json file as well for consistenty (or make both an ini file, but jsons are easier to save, load and manipulate)

**Comment by sfirfi** [comment]
We could do that yeah. I initially choose a ini as they are easier to set up for the most and you can simply edit them via a configparser function, but for saving whole new files or a bunch of edits it might be good to change to json

**Comment by sfirfi** [comment]
Serverwise configs are build in since 7d1e95f54e7bbd0345f67919479d3f5a8777f1e2 now. The general config is still the old one independent form the Configuration class

**Comment by sfirfi** [comment]
Going to close this for now as all the features are implemented. The only thing which could be changed for now is changing the main config to the json format which I think is harder to set up for the most.
