### ISSUE TITLE
Bot errors out when warning a bot user

### ISSUE THREAD

**Issue by Kitty-Therapist** [sfirfi/Bug-Bomber-600#15]
If you warn a bot, Bug Bomber will warn the bot then spit out the command. 

The error should be in the bot logs in our server.

**Comment by Taarek** [comment]
Got a screenshot/traceback of these errors? I don't see why it would throw an error.

**Comment by sfirfi** [comment]
This error was caused because the bot tried to send the other bot a DM that it has been Warned. I will filter this later.

**Comment by Taarek** [comment]
Yeah right, Discord doesn't allow bots to talk to each other in DMs.

**Comment by AEnterprise** [comment]
yeah, bot's can DM other bots, but users can also dissable it

**Comment by sfirfi** [comment]
I filtered the DM to bots now and also added a try catch in the case that a user has disabled the DMs. Will push that soon.

**Comment by sfirfi** [comment]
This has been fixed in 07fc8db79a426371f55f45ca0a5f131f4ef83676
