### ISSUE TITLE
Warning a user with an emote in the end causes the bot to spit out error

### ISSUE THREAD

**Issue by Kitty-Therapist** [sfirfi/Bug-Bomber-600#16]
What I did was:

> !warn Kyle Testing permissions. Don't mind. <3

This has caused the bot to spit out the error, which can be found in bot logs.

**Comment by AEnterprise** [comment]
did we heapen to use utf8 instead of utf8mb4 ?

**Comment by sfirfi** [comment]
Yeah the DB is on the wrong collation. Will fix that on the live DB and add utf8mb4_unicode as default for the sql creation file.

**Comment by AEnterprise** [comment]
nice, kinda stupid that utf8 isn't ut8 but oh well

**Comment by sfirfi** [comment]
The live DB is fixed and the sql file also now makes sure to use utf8mb4_unicode_ci as of 07fc8db79a426371f55f45ca0a5f131f4ef83676
