### ISSUE TITLE
[Feature reques] masked link embed

### ISSUE THREAD

**Issue by ks00908** [sfirfi/Bug-Bomber-600#17]
Command that would send Embed with masked link ( \[name](url) markdown impossible for normal users)
it would be usefull to test bugs similar to 10673
it could be redirecting to main discordpage or even bot repro

**Comment by RMEngelbrecht** [comment]
Probably best to put this one in !userinfo and mask the avatar URL ;)

**Comment by Kitty-Therapist** [comment]
Marking this as a feature request. This will be something that will be added eventually as we made it important that we have features like this for Bug-Bomber since we want it to be mainly for Bug-Hunters to test bugs.

**Comment by Pascal27** [comment]
Maybe even allow us to create custom embeds? We give the input in json form and the bot creates the embed. This tool https://leovoel.github.io/embed-visualizer/ could be helpful for that.

**Comment by sfirfi** [comment]
We're planning to later add bug test support commands which will include things like a embed command, however this is one of the later parts of the bot as we first want to finish the mod utils.

**Comment by Pheonix5555** [comment]
> Probably best to put this one in !userinfo and mask the avatar URL 


I'll do this today for serverinfo and userinfo and anywhere else i can think of masking the URL

**Comment by sfirfi** [comment]
This was added to the user and server info a while again and there also is a temporary maskedlink now which will stay until we have a Embed generator.
