### ISSUE TITLE
Cogs load and unload globally

### ISSUE THREAD

**Issue by Tim-The** [sfirfi/Bug-Bomber-600#30]
cogs get loaded an unloaded globally from the bot

**Comment by Taarek** [comment]
ack'd 

i might do a pr and make it a config thing that only bot owners would be able to do these changes.. I.e enterprise, starshine, ghoul, pheonix and rest of the bba600 mods

**Comment by sfirfi** [comment]
Yeah that's known since we first implemented those commands as they run on the normal permissions system which can be managed by every server owner. I already started to implement a global admin feature but never finished it till now.

**Comment by sfirfi** [comment]
This issue was solved by adding global admins and making the commands only available for those. fc3884ef7c8e70f41eab7846c4310edfce9e7356
