### ISSUE TITLE
Minor Bug with TempMute

### ISSUE THREAD

**Issue by Kitty-Therapist** [sfirfi/Bug-Bomber-600#34]
Currently when you do a +tempmute <user> <duration>, the bot will send a message asking why you are attempting to mute them, then says that the mute role is not set up here as shown here: https://i.imgur.com/5taH1Fs.png

I suspect that may be because of some coding have incorrect indention somewhere. But I'm going to call this a pretty minor bug.

**Comment by Taarek** [comment]
Should be fixed with https://github.com/sfirfi/Bug-Bomber-600/commit/aef840f2bef3b87cea3c2f0d00fbdbc418b7a5cf

Reopen if it's not fixed.
