### ISSUE TITLE
Dog mp4 embed bug

### ISSUE THREAD

**Issue by Kitty-Therapist** [sfirfi/Bug-Bomber-600#6]
Dog embed for mp4 does not show, but only displays the link. [Bug]

**Comment by sfirfi** [comment]
The post of the links is a temporary bypass as we can't add videos to rich embeds currently. This hopefully will change soon. I'm working on a better solution.

**Comment by sfirfi** [comment]
I've removed videos from the Dog command for now. This issue will be closed/
